-- Known marine brands for auto-extraction from product names
CREATE TABLE IF NOT EXISTS known_brands (
  id   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,           -- canonical brand name, e.g. "LIROS"
  aliases text[] NOT NULL DEFAULT '{}', -- alternate spellings / all-caps variants
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Seed with major marine / outdoor brands
INSERT INTO known_brands (name, aliases) VALUES
  ('LIROS',       ARRAY['liros']),
  ('Plastimo',    ARRAY['plastimo']),
  ('Lewmar',      ARRAY['lewmar']),
  ('Harken',      ARRAY['harken']),
  ('Ronstan',     ARRAY['ronstan']),
  ('Spinlock',    ARRAY['spinlock']),
  ('Wichard',     ARRAY['wichard']),
  ('Antal',       ARRAY['antal']),
  ('Schaefer',    ARRAY['schaefer']),
  ('Selden',      ARRAY['selden', 'seldén']),
  ('Rutgerson',   ARRAY['rutgerson']),
  ('Barton',      ARRAY['barton']),
  ('Allen',       ARRAY['allen']),
  ('Holt',        ARRAY['holt']),
  ('Viadana',     ARRAY['viadana']),
  ('Forespar',    ARRAY['forespar']),
  ('Nautos',      ARRAY['nautos']),
  ('Clamcleat',   ARRAY['clamcleat']),
  ('Comar',       ARRAY['comar']),
  ('Karver',      ARRAY['karver']),
  ('Elvstrom',    ARRAY['elvstrom', 'elvström']),
  ('Marlow',      ARRAY['marlow']),
  ('Samson',      ARRAY['samson']),
  ('Yale',        ARRAY['yale']),
  ('Dyneema',     ARRAY['dyneema']),
  ('Spectra',     ARRAY['spectra']),
  ('Garmin',      ARRAY['garmin']),
  ('Raymarine',   ARRAY['raymarine']),
  ('Simrad',      ARRAY['simrad']),
  ('Navionics',   ARRAY['navionics']),
  ('Furuno',      ARRAY['furuno']),
  ('Icom',        ARRAY['icom']),
  ('Standard Horizon', ARRAY['standard horizon','standardhorizon']),
  ('Shakespeare', ARRAY['shakespeare']),
  ('Shakespeare', ARRAY['shakespeare']),
  ('Vesper',      ARRAY['vesper']),
  ('Victron',     ARRAY['victron']),
  ('Mastervolt',  ARRAY['mastervolt']),
  ('Volvo Penta', ARRAY['volvo penta','volvopenta']),
  ('Mercury',     ARRAY['mercury']),
  ('Yamaha',      ARRAY['yamaha']),
  ('Suzuki',      ARRAY['suzuki']),
  ('Honda',       ARRAY['honda']),
  ('Tohatsu',     ARRAY['tohatsu']),
  ('Yanmar',      ARRAY['yanmar']),
  ('Jabsco',      ARRAY['jabsco']),
  ('Rule',        ARRAY['rule']),
  ('Johnson Pump',ARRAY['johnson pump','johnson']),
  ('ITT Jabsco',  ARRAY['itt jabsco']),
  ('Whale',       ARRAY['whale']),
  ('Gusher',      ARRAY['gusher']),
  ('Munster Simms',ARRAY['munster simms']),
  ('Hella Marine',ARRAY['hella marine','hella']),
  ('Osculati',    ARRAY['osculati']),
  ('Perko',       ARRAY['perko']),
  ('Attwood',     ARRAY['attwood']),
  ('SeaDog',      ARRAY['seadog','sea dog']),
  ('Taylor Made', ARRAY['taylor made','taylormade']),
  ('Besto',       ARRAY['besto']),
  ('Spinlock',    ARRAY['spinlock']),
  ('Mullion',     ARRAY['mullion']),
  ('Crewsaver',   ARRAY['crewsaver']),
  ('Secumar',     ARRAY['secumar']),
  ('Survitec',    ARRAY['survitec']),
  ('Ocean Safety',ARRAY['ocean safety']),
  ('McMurdo',     ARRAY['mcmurdo']),
  ('ACR',         ARRAY['acr']),
  ('Kannad',      ARRAY['kannad']),
  ('Jotun',       ARRAY['jotun']),
  ('International',ARRAY['international paints']),
  ('Hempel',      ARRAY['hempel']),
  ('West System', ARRAY['west system','westsystem']),
  ('Epifanes',    ARRAY['epifanes']),
  ('Norglass',    ARRAY['norglass']),
  ('Awlgrip',     ARRAY['awlgrip']),
  ('Interlux',    ARRAY['interlux']),
  ('3M',          ARRAY['3m']),
  ('Sikaflex',    ARRAY['sikaflex','sika']),
  ('Tef-Gel',     ARRAY['tef-gel','tefgel']),
  ('Duralac',     ARRAY['duralac']),
  ('Fernox',      ARRAY['fernox'])
ON CONFLICT (name) DO NOTHING;

-- Add brand column to products if not already there (idempotent)
ALTER TABLE products ADD COLUMN IF NOT EXISTS brand text;
